"""create points_of_interest table

Revision ID: e31ed2dd4daf
Revises: 
Create Date: 2026-08-28 17:01:54.939061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e31ed2dd4daf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_of_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_of_interest_geom'), 'points_of_interest', ['geom'], unique=False)
    op.create_index(op.f('ix_points_of_interest_id'), 'points_of_interest', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_of_interest_id'), table_name='points_of_interest')
    op.drop_index(op.f('ix_points_of_interest_geom'), table_name='points_of_interest')
    op.drop_table('points_of_interest')
    # ### end Alembic commands ###
